version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    restart: always
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Нginx на 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключите свой конфигурационный файл Nginx


networks:
  frontend-network:
    driver: bridge
