version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    restart: always
    networks:
      - frontend-network


networks:
  frontend-network:
    driver: bridge
