
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8005"  # Вы можете оставить это, чтобы тестировать приложение отдельно, но Nginx будет использовать внутреннюю связь
    restart: always
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Nginx на 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключите свой конфигурационный файл Nginx
    networks:
      - frontend-network  # Подключаем nginx к одной сети с frontend

networks:
  frontend-network:
    driver: bridge
