export const exportHeaderParcels = [
  { label: "Дата накладной", key: "date" },
  { label: "Номер накладной", key: "number" },
  { label: "Заказчик", key: "customer" },
  { label: "Город отправителя", key: "sendCity" },
  { label: "Компания отправителя", key: "sendCompany" },
  { label: "Адрес отправителя", key: "sendAddress" },
  { label: "Город получателя", key: "recCity" },
  { label: "Компания получателя", key: "recCompany" },
  { label: "Адрес получателя", key: "recAddress" },
  { label: "Доп.инфо получателя", key: "recAddInfo" },
  { label: "Количество мест", key: "qt" },
  { label: "Фактический вес", key: "weight" },
  { label: "Объемный вес", key: "volume" },
  { label: "Дата последнего статуса", key: "statusDate" },
  { label: "Тип статуса", key: "statusType" },
  { label: "Значение статуса", key: "statusValue" },
  { label: "Стоимость доставки", key: "cost" },
];
